### PR TITLE
Add wrapper recipe section to README

### PR DESCRIPTION
**Pull request by TimvdLippe**
This PR supersedes #168 . The recipe has been transfered to a gist and only mentioned in the README.

### CODE REVIEW

**Comment by jeffposnick** [comment]
Thanks, @TimvdLippe! Could I trouble you for a slight rewording, and then I'll merge?

> Not always are there ready-to-use wrappers built for specific environments, but this list...

can be rewritten as _While there are not always ready-to-use wrappers for specific environments, this list..._

**Comment by TimvdLippe** [comment]
Done 👍

**Comment by jeffposnick** [comment]
👍

**Comment by jeffposnick** [comment]
Thanks!

**Pull request merged**
