### PR TITLE
Downgrade several dependencies for node v0.1x compatibility

### LINKED ISSUE #200: sw-precache 4.2.0, build broken on bower
capture d ecran 2016-10-19 a 16 15 56

Impossible of running grunt script calling sw-precache. 
Fallback to 4.1.0 here seems to be working.

C.

### PR DESCRIPTION
**Pull request by jeffposnick**
R: @addyosmani @gauntface 

This downgrades the version range for the [`pretty-bytes`](https://github.com/sindresorhus/pretty-bytes) dependency. `pretty-bytes` uses `const` starting in version 4.0.0, which was breaking `node` v.0.1x users.

Fixes #200

### CODE REVIEW

**Comment by jeffposnick** [comment]
Travis CI completed this time (yay!) and picked up some more modules that need to be fiddled with for node v0.12 compatibility. I don't currently have that version installed, so I'm dependent on Travis finding the issues. Hold off on merging, obviously, until Travis is happy.

**Comment by addyosmani** [comment]
Waiting SGTM

**Comment by jeffposnick** [comment]
Okay, node v0.12 is happy now, as [per Travis CI](https://travis-ci.org/GoogleChrome/sw-precache/jobs/168986413).

I had to bump down all of the various `eslint`-related modules to the version that we were previously using rather than untangle the thicket of cross-dependencies, given that we can't use the latest version of some of them.

**Comment by jeffposnick** [comment]
Should be ready to merge. Okay with you, @addyosmani?

**Pull request merged**
