### PR TITLE
Docs for the new dynamicUrlToDependencies option

### PR DESCRIPTION
**Pull request by jeffposnick**
R: @gauntface @addyosmani 
CC: @HenrikJoreteg to confirm I'm explaining it properly.

### CODE REVIEW

**Comment by HenrikJoreteg** [comment]
This explanation sounds good to me... thanks for doing this so quickly.

**Comment by gauntface** [comment]
LGTM

**Comment by HenrikJoreteg** [comment]
@jeffposnick thanks again for this, any idea when you'll publish the updated version to npm?

**Comment by jeffposnick** [comment]
Yup—I'm going to be taking a long international flight soon, and don't want to push a new minor release out just before being offline for an extended period. Look for the release early next week.

**Comment by HenrikJoreteg** [comment]
cool, thanks @jeffposnick

**Pull request merged**
