### PR TITLE
wasn't stripping dist from URL

### PR DESCRIPTION
**Pull request by karolklp**

### CODE REVIEW

**Comment by karolklp** [comment]
"Thanks, your CLA has been submitted." :)

**Comment by jeffposnick** [comment]
Hello @karolklp—sorry for the delay in looking at this. The code as-is seems to be working for me, but I'm on OS X. Are you using Windows, by any chance? Could you describe the failure in more detail?

**Comment by karolklp** [comment]
It still doesn't work for me. I'm on Windows 8.1.

Gulp serve-dist in demo is building cache file with "dist" in URL
```
var PrecacheConfig = [["dist/css/main.css" ...
```
so in Service Worker's console we get
> Request for http://localhost:3000/dist/css/main.css?sw-precache=1431326291764 returned a response with status 404, so not attempting to cache it.

It's nice, that in Chrome Canary (44) it's written in console. In Chrome Stable - 42 the only thing you get in console (not SW console, but in webpage console) is 

> Content is cached, and will be available for offline use the next time the page is loaded.


after my change, PrecacheConfig build from gulp tast looks like this: 
```
var PrecacheConfig = [["/css/main.css" ...
```
and it's working :)

**Comment by jeffposnick** [comment]
Thanks, Karol. I hadn't tested the demo on Windows previously.

I made a slightly different change in https://github.com/GoogleChrome/sw-precache/commit/983e4b24b4aeca89d68706669b1259eb34189776 that should accomplish the same thing, but I wanted the final path to be a relative URL, so I'm stripping out the leading '/' character as well.

**Pull request closed without merging**
