### PR TITLE
Make the stripPrefix option only strip the prefix in a filename

### PR DESCRIPTION
**Pull request by marco-c**
Currently sw-precache is stripping the first occurrence of `stripPrefix`, but the first occurrence could be in the middle of the name.

### CODE REVIEW

**Comment by marco-c** [comment]
The remaining lint issues are in a file that I haven't modified.

**Comment by jeffposnick** [comment]
Thanks for the patch! It looks good in general, but could you confirm that you've signed the Google CLA? @googlebot doesn't seem to have picked it up if you have.

(I'm not sure what's going on with the Travis CI checks, but I can't reproduce the failures locally and I'm willing to chalk it up to something unrelated.)

**Comment by marco-c** [comment]
Sorry for the delay, I'm waiting to be added to my company's authorized contributor list.

**Comment by marco-c** [comment]
I'm now covered by the CLA between Mozilla and Google.

**Comment by jeffposnick** [comment]
Thanks, @marco-c!

**Pull request merged**
