### PR TITLE
dynamicUrlToDependencies: Support Buffers alongside strings

### PR DESCRIPTION
**Pull request by papandreou**
I need this to declare dependencies that aren't text based.

### CODE REVIEW

**Comment by papandreou** [comment]
I signed it!

**Comment by papandreou** [comment]
Rebased and fixed conflicts.

Ping?

**Comment by jeffposnick** [comment]
Thanks for the contribution!

**Comment by papandreou** [comment]
@jeffposnick Thanks for merging :). How about a new release?

**Comment by addyosmani** [comment]
As our last release was in early May and there have been a few other minor changes made to master since, another release (when time works for @jeffposnick) sgtm.

**Comment by jeffposnick** [comment]
Yup! I want to do another sweep through the open issues to see if there's anything pressing that needs to be addressed first.

**Comment by jeffposnick** [comment]
This was included in the `5.2.0` release: https://github.com/GoogleChrome/sw-precache/releases/tag/5.2.0

**Pull request merged**
