### PR TITLE
Markdown fixes to README.md

### PR DESCRIPTION
**Pull request by humphd**
I've really appreciated the quality of the docs for sw-precache, and the help in bugs--thanks for both.  As I was re-reading things today, I noticed a few small markdown issues, which I've fixed.

### CODE REVIEW

**Comment by humphd** [comment]
I signed it.

**Comment by jeffposnick** [comment]
Thanks, and apologies for the messiness in the docs! Unfortunately, those edits are to auto-generated headings, created via https://github.com/GoogleChrome/sw-precache/blob/master/gulpfile.js#L32

I need to tweak that logic there, and that should take care of it moving forward. (Not sure what changed to break that logic.)

**Comment by jeffposnick** [comment]
See https://github.com/GoogleChrome/sw-precache/issues/280

**Comment by humphd** [comment]
NOTE: not all of the changes are of the type that's autogenerated (e.g. you have some things that should be links, but aren't due to extra whitespace, missing parents, etc.

**Comment by jeffposnick** [comment]
Ah, thanks—I just cleaned that up manually in https://github.com/GoogleChrome/sw-precache/commit/17d33a9dc4ff22030057074602c7d60bf151eb6c

**Pull request closed without merging**
